class Settings:
    SCREEN_WIDTH = 1000
    SCREEN_HEIGHT = 800

    FPS = 60
    UI_MENU_SCALE = 2
    UI_GAME_SCALE = 1.0
    ASSETS_SCALE = 1

    ASTEROID_SPAWN_INTERVAL = 1
    UFO_SPAWN_INTERVAL = 15

    PLAYER_SPEED = 300
    TURNING_INTENSITY = 4
    PLAYER_HEALTH = 5
    INVINCIBILITY = False
    PLAYER_SHOOT_COOLDOWN = 0.25
    SHIELD_DURATION = 5
    SHIELD_COOLDOWN = 10

    BULLET_SPEED = 500

    UFO_SPEED = 150
    UFO_SHOOT_COOLDOWN = 2.0

    MUSIC_ON = True
    SOUND_ON = True
    MUSIC_VOLUME = 0.5
    SOUND_VOLUME = 1